import menu from "./modules/menu.js";
import noite from "./modules/noite.js";
import modoNoturno from "./modules/modo_noturno.js";
import textoAnimado from "./modules/texto_animado.js";
import projetos from "./modules/projetos.js";
import iniciarScrollSuave from "./modules/scroll_suave.js";
import iniciarAnimacaoScroll from "./modules/anima_scroll.js";
import esconderMenu from "./modules/esconder_menu.js";
import carrossel from "./modules/carrossel.js";
import radio from "./modules/radio.js";
import download from "./modules/download.js";
menu();
noite();
modoNoturno();
textoAnimado();
projetos();
iniciarScrollSuave();
iniciarAnimacaoScroll();
esconderMenu();
carrossel();
radio();
download();
